### **np.sort**

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)

a

array([35,  6, 61, 24, 98, 56, 72, 18, 79,  2, 68, 91, 35, 72, 57])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[94, 14, 53, 83],
       [86, 57, 57, 55],
       [32, 27,  7, 65],
       [15,  2, 50, 48],
       [89, 26, 79, 55],
       [17, 63, 64, 11]])

In [4]:
np.sort(a)[::-1]

array([98, 91, 79, 72, 72, 68, 61, 57, 56, 35, 35, 24, 18,  6,  2])

In [5]:
np.sort(b,axis=0)   # 0 -> column, 1 -> row

array([[15,  2,  7, 11],
       [17, 14, 50, 48],
       [32, 26, 53, 55],
       [86, 27, 57, 55],
       [89, 57, 64, 65],
       [94, 63, 79, 83]])

### **np.append**

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [6]:
# code
np.append(a,200)

array([ 35,   6,  61,  24,  98,  56,  72,  18,  79,   2,  68,  91,  35,
        72,  57, 200])

In [7]:
b

array([[94, 14, 53, 83],
       [86, 57, 57, 55],
       [32, 27,  7, 65],
       [15,  2, 50, 48],
       [89, 26, 79, 55],
       [17, 63, 64, 11]])

In [8]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[9.40000000e+01, 1.40000000e+01, 5.30000000e+01, 8.30000000e+01,
        2.27836659e-02],
       [8.60000000e+01, 5.70000000e+01, 5.70000000e+01, 5.50000000e+01,
        9.78554021e-01],
       [3.20000000e+01, 2.70000000e+01, 7.00000000e+00, 6.50000000e+01,
        1.55303443e-01],
       [1.50000000e+01, 2.00000000e+00, 5.00000000e+01, 4.80000000e+01,
        7.17240467e-01],
       [8.90000000e+01, 2.60000000e+01, 7.90000000e+01, 5.50000000e+01,
        3.97472757e-01],
       [1.70000000e+01, 6.30000000e+01, 6.40000000e+01, 1.10000000e+01,
        8.74229977e-01]])

### **np.concatenate**

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [9]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [10]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### **np.unique**

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [12]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [13]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### **np.expand_dims**

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [ ]:
# code
a.shape

(15,)

In [ ]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [14]:
np.expand_dims(a,axis=1).shape

(15, 1)

In [ ]:
np.expand_dims(a,axis=1)

array([[11],
       [53],
       [28],
       [50],
       [38],
       [37],
       [94],
       [92],
       [ 5],
       [30],
       [68],
       [ 9],
       [78],
       [ 2],
       [21]])

### **np.where**

The numpy.where() function **returns the indices** of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [15]:
a

array([35,  6, 61, 24, 98, 56, 72, 18, 79,  2, 68, 91, 35, 72, 57])

In [16]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 2,  4,  5,  6,  8, 10, 11, 13, 14]),)

###replace all values > 50 with 0
**np.where(condition,True,false)**

In [18]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([35,  6,  0, 24,  0,  0,  0, 18,  0,  2,  0,  0, 35,  0,  0])

In [19]:
np.where(a%2 == 0,0,a)

array([35,  0, 61,  0,  0,  0,  0,  0, 79,  0,  0, 91, 35,  0, 57])

### **np.argmax**

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [20]:
# code
a

array([35,  6, 61, 24, 98, 56, 72, 18, 79,  2, 68, 91, 35, 72, 57])

In [21]:
np.argmax(a)

np.int64(4)

In [24]:
b

array([[94, 14, 53, 83],
       [86, 57, 57, 55],
       [32, 27,  7, 65],
       [15,  2, 50, 48],
       [89, 26, 79, 55],
       [17, 63, 64, 11]])

In [25]:
np.argmax(b,axis = 0)

array([0, 5, 4, 0])

In [26]:
np.argmax(b,axis=1)

array([0, 0, 3, 2, 0, 2])

### **np.argmin()**

In [27]:
# np.argmin
np.argmin(a)

np.int64(9)

### **np.cumsum**

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [28]:
a

array([35,  6, 61, 24, 98, 56, 72, 18, 79,  2, 68, 91, 35, 72, 57])

In [29]:
np.cumsum(a)

array([ 35,  41, 102, 126, 224, 280, 352, 370, 449, 451, 519, 610, 645,
       717, 774])

In [30]:
b

array([[94, 14, 53, 83],
       [86, 57, 57, 55],
       [32, 27,  7, 65],
       [15,  2, 50, 48],
       [89, 26, 79, 55],
       [17, 63, 64, 11]])

In [31]:
np.cumsum(b)

array([  94,  108,  161,  244,  330,  387,  444,  499,  531,  558,  565,
        630,  645,  647,  697,  745,  834,  860,  939,  994, 1011, 1074,
       1138, 1149])

In [32]:
np.cumsum(b,axis = 0)

array([[ 94,  14,  53,  83],
       [180,  71, 110, 138],
       [212,  98, 117, 203],
       [227, 100, 167, 251],
       [316, 126, 246, 306],
       [333, 189, 310, 317]])

###**np.cumprod()**

In [33]:
# np.cumprod
np.cumprod(a)

array([                 35,                 210,               12810,
                    307440,            30129120,          1687230720,
              121480611840,       2186651013120,     172745430036480,
           345490860072960,   23493378484961280, 2137897442131476480,
       1039434179763470336, 1052284648131657728, 4639992722375835648])

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

### **np.percentile**

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [34]:
np.percentile(a,100)

np.float64(98.0)

In [36]:
np.percentile(a,0)

np.float64(2.0)

In [37]:
np.percentile(a,50)

np.float64(57.0)

In [38]:
np.median(a)

np.float64(57.0)

### **np.histogram**

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [39]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([2, 1, 1, 2, 0, 2, 2, 3, 0, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [40]:
np.histogram(a,bins = [0,50,100])

(array([6, 9]), array([  0,  50, 100]))

### **np.corrcoef**

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [41]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### **np.isin**

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [46]:
# code
a


array([35,  6, 61, 24, 98, 56, 72, 18, 79,  2, 68, 91, 35, 72, 57])

In [47]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([], dtype=int64)

### ***np.flip***

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [48]:
# code
a

array([35,  6, 61, 24, 98, 56, 72, 18, 79,  2, 68, 91, 35, 72, 57])

In [49]:
np.flip(a)

array([57, 72, 35, 91, 68,  2, 79, 18, 72, 56, 98, 24, 61,  6, 35])

In [50]:
b

array([[94, 14, 53, 83],
       [86, 57, 57, 55],
       [32, 27,  7, 65],
       [15,  2, 50, 48],
       [89, 26, 79, 55],
       [17, 63, 64, 11]])

In [51]:
np.flip(b,axis=1)

array([[83, 53, 14, 94],
       [55, 57, 57, 86],
       [65,  7, 27, 32],
       [48, 50,  2, 15],
       [55, 79, 26, 89],
       [11, 64, 63, 17]])

### **np.put**

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [56]:
# code
a

array([350, 600,  61,  24,  98,  56,  72,  18,  79,   2,  68,  91,  35,
        72,  57])

In [57]:
np.put(a,[0,1],[350,600])

### **np.delete**

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [58]:
# code
a

array([350, 600,  61,  24,  98,  56,  72,  18,  79,   2,  68,  91,  35,
        72,  57])

In [59]:
np.delete(a,[0,2,4])

array([600,  24,  56,  72,  18,  79,   2,  68,  91,  35,  72,  57])

### Set functions

- **np.union1d(m,n)**
- **np.intersect1d(m,n)**
- **np.setdiff1d(m,n)**
- **np.setxor1d(m,n)**
- **np.in1d(m,n)**

###**np.union1d(m,n)**

In [60]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [61]:
np.intersect1d(m,n)

array([3, 4, 5])

In [63]:
np.setdiff1d(m,n)

array([1, 2])

In [64]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
m[np.in1d(m,1)]

array([1])

### **np.clip**

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [65]:
# code
a

array([350, 600,  61,  24,  98,  56,  72,  18,  79,   2,  68,  91,  35,
        72,  57])

In [66]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 61, 25, 75, 56, 72, 25, 75, 25, 68, 75, 35, 72, 57])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals