### What is numpy?

NumPy is the fundamental package for **scientific computing** in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

- Earlier Python was a slow language but its syntax is convinean, but we needed a fast language so someone, created a data type 'array' in C which was fast and integrated it into python language, which solved the problem.

### Creating Numpy Arrays

In [3]:
#np.array
# 1D array -> Vector

import numpy as np
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


### 2D and 3D np.array

In [4]:
# 2D array -> Matrix
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
#  3D array -> Tensor

c = np.array([[[1,2],[4,5]],[[6,7],[8,9]]])
print(c)



[[[1 2]
  [4 5]]

 [[6 7]
  [8 9]]]


### **dtype** =  
We can also create a different data types array (different than integer) using "**dtype**" parameter

In [6]:
#dtype -> float, complex, boolean etc
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

### **np.arange()**
we can create an array of range of numbers just like the **range** function.



In [7]:
#
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

### **.reshape()**
to reshape the data.

In [9]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

### **np.ones()**
To create an array with all the elements "1".
- It's used to initialize.

In [10]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### **np.zeros()**
To create an array with all the elements "0".
- It's used to initialize.


```
# This is formatted as code
```




In [11]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

###**np.random**

In [12]:
np.random.random((4,5))

array([[0.68342241, 0.05144688, 0.08217808, 0.99181507, 0.24824098],
       [0.0246979 , 0.72057377, 0.40401863, 0.42869471, 0.25696534],
       [0.18139535, 0.81231065, 0.39921026, 0.10210493, 0.50834349],
       [0.62459243, 0.86470066, 0.75345998, 0.43380293, 0.94982404]])

###**np.linspace(start_point, end_point, no._of_points)**
- Creates linearly seperable points, creates number of points at equal distance between starting point and ending point.

In [13]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

###**np.identity()**
To create an identity matrix

In [14]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Array Attributes

In [15]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

### **.ndim**
return the dimension of an array

In [16]:
a2.ndim

2

###**.shape**
returns the shape of the array.

In [17]:
a3.shape

(2, 2, 2)

###**.size**
gives the number of items in array.

In [18]:
a2.size

12

###**.itemsize**
-how much size every item is occupying in RAM.

In [19]:
a2.itemsize

8

###**.dtype**

gives the data type.

In [20]:
a3.dtype

dtype('int64')

###Changing Datatype
**astype(np.int32)**

- Used to change the data type such as float to int, just to save the memory, because we have to work on big data and if we are confident about certaing part of our data that, the datatype used in that is unnecessary occupying the extra space, we can change the datatype to save the memory.

In [21]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [22]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Scalar Operations
operation with a **constant**
- we can use all arithmetic operations on arrays

In [23]:
# arithmetic
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

### Relational Operator

In [24]:
a1 > 8

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [25]:
a1 < 5

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

### Vector Operations
-  Just like all the matrix operations.

In [26]:
# arithmetic

a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [27]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

### Array Functions


In [28]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[ 3., 28., 20.],
       [22.,  7., 97.],
       [25., 74., 76.]])

### np.max / np.min / np.sum / np.prod

###**np.max()**

In [29]:
np.max(a1)

np.float64(97.0)

###**np.min()**

In [30]:
np.min(a1)

np.float64(3.0)

###**np.sum()**
- Return sum of all the items.

In [31]:
np.sum(a1)

np.float64(352.0)

###**np.prod()**
- Return product of all the numbers in array

In [32]:
np.prod(a1)

np.float64(3528475104000.0)

### **axis = 1** (for row wise operations)
### **axis = 0** (for column wise operations)

- If we want to apply all the above operations row or column wise we can use axis = 0 or 1 parameter.

In [33]:
np.min(a1, axis = 1)

array([ 3.,  7., 25.])

In [34]:
np.max(a1,axis = 0)

array([25., 74., 97.])

### Statistical Functions

### **np.mean()**
- return the mean of complete array.

###**axis = 0 or 1** here also we can use axis parameter.

In [35]:
np.mean(a1)

np.float64(39.111111111111114)

In [36]:
np.mean(a1, axis = 1)

array([17.        , 42.        , 58.33333333])

###**np.median()**

In [37]:
np.median(a1)

np.float64(25.0)

###**np.std()**

In [38]:
np.std(a1)

np.float64(32.050115078470625)

###**np.var()**

In [39]:
np.var(a1)

np.float64(1027.20987654321)

### Trigonometric Functions

### **sin/cos/tan etc**

In [40]:
np.sin(a1)

array([[ 0.14112001,  0.27090579,  0.91294525],
       [-0.00885131,  0.6569866 ,  0.37960774],
       [-0.13235175, -0.98514626,  0.56610764]])

### **np.dot()**
- To calculate the dot product. ()to multiply 2 matices.

In [41]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [42]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

###**np.log()**

In [43]:
np.log(a1)

array([[1.09861229, 3.33220451, 2.99573227],
       [3.09104245, 1.94591015, 4.57471098],
       [3.21887582, 4.30406509, 4.33073334]])

###**np.exp()**

In [44]:
np.exp(a1)

array([[2.00855369e+01, 1.44625706e+12, 4.85165195e+08],
       [3.58491285e+09, 1.09663316e+03, 1.33833472e+42],
       [7.20048993e+10, 1.37338298e+32, 1.01480039e+33]])

### round
###**np.round()**
- To round off the numbers to its nearest integer.


In [45]:
np.round(np.random.random((2,3))*100)

array([[25., 90., 15.],
       [22., 24., 56.]])

### floor
###**np.floor()**
- To round off the numbers to its last integer.()like the greatest integer function.


In [46]:
np.floor(np.random.random((2,3))*100)

array([[11., 18., 76.],
       [46., 20., 60.]])

### floor
###**np.ceil()**
- To round off the numbers to its next integer.()like the smallest integer function.


In [47]:
np.ceil(np.random.random((2,3))*100)

array([[45., 79., 63.],
       [47., 18., 89.]])

### Indexing and Slicing
-  Same as List

In [48]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [49]:
a1[-1]

np.int64(9)

In [50]:
print(a1[0])

0


In [51]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
a2[1,2]

np.int64(6)

In [53]:
a2[2,3]

np.int64(11)

In [54]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [55]:
a3[1,0,1]

np.int64(5)

### Slicing
- Used to fetch the multiple items.

slicing in 1D

In [56]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a1[2:5]

array([2, 3, 4])

In [58]:
a1[2:5:2]

array([2, 4])

Slicing in 2D

In [59]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
# for 1 row
a2[0,:]

array([0, 1, 2, 3])

In [61]:
# for 3rd columns
a2[:,2]

array([ 2,  6, 10])

In [62]:
# for 5,6 and 9,10
a2[1:4,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [63]:
# for 0,3, 8, 11
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [64]:
# for 1, 3 , 9, 11
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [65]:
# for 4, 7
a2[1,::3]

array([4, 7])

In [66]:
# for 1,2,3 and 5,6 7
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

Slicing in 3D array

In [67]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [68]:
# for 2nd 2D matrix
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [69]:
# for 1st and 3rd 2D matrix
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [70]:
# for 1 2D matrix's 2 row
a3[0,1]

array([3, 4, 5])

In [71]:
# for 2nd np array middle column

a3[1,:,1]

array([10, 13, 16])

In [72]:
# for 22,23,25,26
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [73]:
# for 0,2,18,20
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### **Iterating**

In [77]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [78]:
a2

for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [79]:
a3

for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


### **np.nditer():**

- it converts any dimensional array into 1 dimension.

In [80]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping
-Already done.

## Transpose
- Changes rows <-> columns

### **np.transpose(a2)**

### or **a2.T**

In [81]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [84]:
# or
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## ravel

**a3.ravel()**

It changes any dimensional array into 1 Dimansional array.

In [85]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [86]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Stacking
- Joining the any number of arrays.

#### 1. Horizontal stacking

**np.hstack((__,__))**

In [87]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [89]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

####2. Vertical stacking

**np.vstack((__,__))**

In [92]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting

####1. horizontal splitting

**`np.hsplit(-, no. of parts)`**

In [93]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

####2. Vertical splitting

**`np.vsplit(-, no. of parts)`**

In [96]:
a4.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [97]:
np.vsplit(a4.T,2)

[array([[0, 4, 8],
        [1, 5, 9]]),
 array([[ 2,  6, 10],
        [ 3,  7, 11]])]